# Generated by Django 5.0.1 on 2024-01-12 14:15

import django.core.validators
import django.db.models.deletion
import video_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(help_text='Upload only MP4, MPG, or MPEG files', upload_to=video_app.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mpg', 'mpeg'])])),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=255)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
