# Generated by Django 5.0.1 on 2024-01-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_video_video_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_slug',
        ),
        migrations.AlterField(
            model_name='video',
            name='create_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
