# Generated by Django 5.0.1 on 2024-01-13 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party_app', '0002_alter_party_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='video_url',
            new_name='video',
        ),
    ]
