# Generated by Django 5.0.1 on 2024-01-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party_app', '0003_rename_video_url_party_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='id',
        ),
        migrations.AlterField(
            model_name='party',
            name='state',
            field=models.BooleanField(default=False, primary_key=True, serialize=False),
        ),
    ]
